name: CI

inputs:
  environment:
    required: true
    description: "Environment"
    type: string

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build
      run: npm run build
      shell: bash
